### ISSUE TITLE
Neovim diff not highlighting properly

### ISSUE THREAD

**Issue by ikirudennis** [the-mikedavis/tree-sitter-diff#10]
Firstly, I'm not sure if this is the right place to report this...

Like some other users, I ran into [an issue](https://github.com/tpope/vim-fugitive/issues/2091) with neovim not highlighting diffs in gitcommit correctly. In the process of trying to solve that problem for myself, I created a diff file, and noticed that when I opened that with neovim, I also experience the same lack of highlighting. I'm able to get the highlighting issuing a command to toggle the treesitter highlighting.

Given that it's happening in both `gitcommit` filetypes and `diff` filetypes, that's how I ended up thinking that maybe this repo is the correct place to file this issue. If I'm wrong on that assumption though, can you guide me to where this issue should be filed?

Thanks!

**Comment by the-mikedavis** [comment]
I don't use neovim so I probably won't be of much help here. You might have better luck posting in the nvim-treesitter repository. I last updated the grammar and regenerated the bindings two weeks ago in https://github.com/the-mikedavis/tree-sitter-diff/commit/886bb5122a8e9a3b759efe24fa208856f75eceaa (and the child commit) but I don't know how that could make the nvim highlighting fail - the node I removed isn't used by nvim-treesitter's highlight queries: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/diff/highlights.scm. I tried updating to the latest revision in Helix as well and I don't see any breakages for the highlights

**Comment by ikirudennis** [comment]
Thanks for the info, I'll start barking up that tree... sitter :zany_face:

**Comment by ikirudennis** [comment]
Good news: upon digging into it a little more, it looks like this is a [breaking change](https://www.reddit.com/r/neovim/comments/19aratu/psa_nvimtreesitter_breaking_changes_on_highlight/) introduced into how highlighting works in neovim, and that some colorschemes have updated to reflect these changes, while others have not yet. So, everything is working as intended, and I need to file an issue with the colorscheme I use.

Thanks, again!
