### ISSUE TITLE
[FR] Support diff3/zdiff3

### ISSUE THREAD

**Issue by jtrv** [the-mikedavis/tree-sitter-diff#14]
It would be nice to see support for diff3 and zdiff3 merge conflicts within tree-sitter-diff,  as it roughly falls under the category of "diff".

[Here is a rundown of diff3 and zdiff3](https://git-scm.com/docs/git-merge/2.38.0#_how_conflicts_are_presented) for those unfamiliar with it.

**Comment by the-mikedavis** [comment]
Conflict markers and diff syntax are totally separate as far as I know. This grammar covers diffs like you might get from `diff` or in a verbose git commit rather than highlighting conflicts.
