### ISSUE TITLE
Highlight of a patch file does not work with nvim-treesitter and the `diff` parser

### ISSUE THREAD

**Issue by xulongwu4** [the-mikedavis/tree-sitter-diff#5]
Hi, I have some problems in getting the `diff` parser to highlight my patch file correctly. Can you give me some help with figuring out what could be wrong in my configuration?

I am using the lastest nvim-treesitter commit in the master branch, and my minimum `init.lua` file is as follows:

```lua
require'nvim-treesitter.configs'.setup {
  -- A list of parser names, or "all" (the four listed parsers should always be installed)
  ensure_installed = { "diff" },

  -- Install parsers synchronously (only applied to `ensure_installed`)
  sync_install = false,

  highlight = {
    -- `false` will disable the whole extension
    enable = true,

    -- Setting this to true will run `:h syntax` and tree-sitter at the same time.
    -- Set this to `true` if you depend on 'syntax' being enabled (like for indentation).
    -- Using this option may slow down your editor, and you may see some duplicate highlights.
    -- Instead of true it can also be a list of languages
    additional_vim_regex_highlighting = false,
  },
}
```

This is the result of opening a patch file:
![image](https://user-images.githubusercontent.com/16892446/214074882-4dbc5f86-3932-4625-902f-4eea8645c255.png)

If I disable the highlight module in treesitter, then nvim highlights the patch file properly:
![image](https://user-images.githubusercontent.com/16892446/214075210-9a5b9911-75df-4ff6-885e-d28081e0b623.png)

Output of `nvim --version`:

```
NVIM v0.9.0-dev-737+g0aae7f386
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/__w/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/__w/neovim/neovim/.deps/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src
Compiled by root@6027050758c9
```

**Comment by the-mikedavis** [comment]
I don't use nvim so I'm not totally sure how to debug this - you may want to open this issue against nvim-treesitter instead.

It looks like additions and removals are not highlighted: those are highlighted with two new scopes in the nvim-treesitter queries https://github.com/nvim-treesitter/nvim-treesitter/commit/1e4b23c26678bd36e3da638183996eaa30e7fba8#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R207-R208. I'm not sure how theming works for nvim with tree-sitter but you may need to add colors for the `text.diff.add` and `text.diff.delete` scopes to your theme?

**Comment by xulongwu4** [comment]
Yes, you are right. After I added highlight groups for `text.diff.add` and `text.diff.delete`, the patch file is highlighted correctly. It turned out that I have been using color schemes that don't have proper support for these two groups. Thanks for your help!

**Comment by dakyskye** [comment]
@xulongwu4 hi, can you provide me with the snippet of your fix?

**Comment by xulongwu4** [comment]
@dakyskye, you just need to make sure the colorscheme you are using defines the highlight groups `@text.diff.add` and `@text.diff.delete`.

If they are not defined, you can use the following two command:

```viml
hi link @text.diff.add DiffAdd
hi link @text.diff.delete DiffDelete
```

**Comment by mostlyobvious** [comment]
It seems those groups have changed again: https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R222-R224
