### ISSUE TITLE
No syntax highlighting by default

### ISSUE THREAD

**Issue by dakyskye** [the-mikedavis/tree-sitter-diff#7]
What I did:

* ensured I've the grammar installed (TSInstall diff)
* made random changes to files
* ran `git diff | nvim`
here is what I got:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/32128756/219884514-a252bb83-297d-4355-abc6-868a4e2af4bd.png">

that confused me.. I ran `TSUninstall diff` and surprisingly I got proper syntax highlighting:
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/32128756/219884552-14b4455b-67aa-4165-b2b2-3446b0e3555c.png">

any idea what might be wrong?

**Comment by the-mikedavis** [comment]
I suspect that this is the same problem as https://github.com/the-mikedavis/tree-sitter-diff/issues/5

**Comment by dakyskye** [comment]
@the-mikedavis oh, I am sorry I skimmed through the issues too quickly before opening this one.. and thanks 🙏
