### ISSUE TITLE
remove --git assumption

### ISSUE THREAD

**Issue by jan-xyz** [the-mikedavis/tree-sitter-diff#9]
I just ran into the issue that is marked as FIXME [here](https://github.com/the-mikedavis/tree-sitter-diff/blob/c165725c28e69b36c5799ff0e458713a844f1aaf/grammar.js#L67). What's needed to remove the assumption? Do you have plan how it should behave and what it maybe has in terms of edge cases?

**Comment by the-mikedavis** [comment]
Actually I'm not really sure. When I wrote that I was wondering if there are any other strings other than `--git` we might see there. And if we do see other strings there - would be we able to parse them the same way.

Do you have another format that you were looking to support?

**Comment by jan-xyz** [comment]
The code-action diff in the LSP protocol uses the same format and some authors are then using `git --code-action...` in the first line to pump it also through alternative tools like `delta`.

EDIT: I ran into this [here](https://github.com/aznhe21/actions-preview.nvim/pull/34)

**Comment by the-mikedavis** [comment]
The `--code-actions` is just cosmetic for that plugin, right? I think it makes sense for the diff there to be `diff --git` like in your PR.

I don't feel strongly about keeping `--git` though. It seems fine to accept anything after `diff`. If it isn't a git diff then the parser will fail anyways

**Comment by jan-xyz** [comment]
I pondered on this a bit, I think it is nice if the parser is a bit more flexible here to support a best-effort on highlighting it correctly. Currently the top line of a diff looks strange if the `--git` argument is missing and I think in terms of user experience it'd be nice if you can vary there a bit, like the above example. On the other hand I also see the point that creativity at this point is wild, because in the end it is an invalid command that wouldn't run or be generated usually.

**Comment by the-mikedavis** [comment]
Fixed in 886bb5122a8e9a3b759efe24fa208856f75eceaa

**Comment by jan-xyz** [comment]
Nice!
